= add-deb-repo

Add a new file with debian repository description to `/etc/apt/sources.list.d` directory.

Step syntax:

....
- name: <name>
  uses: myci-actions/add-deb-repo@<version>
  with:
    repo: <repo>
    repo-name: <repo-name>
    keys: <keys>
    key-server: <key-server>
    update: <perform-update>
    install: <packages-to-install>
....

Arguments:

- `<name>` - Action step name.
- `<version>` - Action version.
- `<repo>` - Debian repository entry as it appears in `sources.list` file
- `<repo-name>` - Name of the repository. This will be the filename in the `/etc/apt/sources.list.d` directory.
- `<keys>` - Repository keys to import. Optional. Empty by default.
- `<key-server>` - Key server to import keys from. Optional. Empty by default. If `keys` parameter is not specified, then `key-server` represents direct URL to the key.
- `<perform-update>` - Perform final `apt update`. Optional. Default value: `true`.
- `<packages-to-install>` - space separated list of packages to install after adding the repo. Update will be performed first.


Step example:
....
- name: add custom deb repository
  uses: myci-actions/add-deb-repo@8
  with:
    repo: deb http://dl.bintray.com/igagis/debian buster main
    repo-name: igagis
    keys: 379CE192D401AB61
    key-server: keyserver.ubuntu.com
....
