= add-deb-repo

Add a new file with debian repository description to `/etc/apt/sources.list.d` directory.

Step syntax:

....
- name: <name>
  uses: myci-actions/add-deb-repo@<version>
  with:
    repo: <repo>
    repo-name: <repo-name>
    keys-asc: <keys-asc-url>
    update: <perform-update>
    install: <packages-to-install>
....

Arguments:

- `<name>` - Action step name.
- `<version>` - Action version.
- `<repo>` - Debian repository entry as it appears in `sources.list` file
- `<repo-name>` - Name of the repository. This will be the filename in the `/etc/apt/sources.list.d` directory.
- `<keys-asc-url>` - URL to ascii armored keys keyring. The file is downloaded and is placed to `/etc/apt/trusted.gpg.d/<repo-name>.asc`.
- `<perform-update>` - Perform final `apt update`. Optional. Default value: `true`.
- `<packages-to-install>` - space separated list of packages to install after adding the repo. Update will be performed first. Optional. Empty by default.


Step example:
....
- name: add custom deb repository
  uses: myci-actions/add-deb-repo@11
  with:
    repo: deb https://gagis.hopto.org/repo/cppfw/debian buster main
    repo-name: cppfw
    keys-asc: https://gagis.hopto.org/repo/cppfw/pubkey.gpg
....
