name: ci
on: [push, pull_request]
jobs:
  linux_container_keys_asc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, codename: stretch, image_owner: , package_type: deb}
          - {os: debian, codename: buster, image_owner: , package_type: deb}
          - {os: ubuntu, codename: bionic, image_owner: , package_type: deb}
          - {os: ubuntu, codename: focal, image_owner: , package_type: deb}
    runs-on: ubuntu-latest
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    name: linux container keys-asc - ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    steps:
      - name: cehckout repo
        uses: actions/checkout@v3
      - name: add cppfw deb repo
        uses: ./
        with:
          repo: deb http://gagis.hopto.org/repo/cppfw/${{ matrix.os }} ${{ matrix.codename }} main
          keys-asc: http://gagis.hopto.org/repo/cppfw/pubkey.gpg
      - name: apt update
        run: apt update
  linux_keys_asc:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout repo
        uses: actions/checkout@v3
      - name: add cppfw deb repo
        uses: ./
        with:
          repo: deb http://gagis.hopto.org/repo/cppfw/ubuntu focal main
          repo-name: cppfw
          keys-asc: http://gagis.hopto.org/repo/cppfw/pubkey.gpg
      - name: apt update
        run: sudo apt update
